#!/usr/bin/env ruby

require 'kyougi'

module Kyougi
  class CLI < Thor
    register Kyougi::Commands::Generate,
      'generate',
      'generate NAME',
      'Generate Project'
  end
end

Kyougi::CLI.start(ARGV)
